

/*
QUERY REPORT  FUNCTIONS
*/



CREATE OR REPLACE FUNCTION PSR_REPORT(INGESTION_START TIMESTAMP_NTZ(9), INGESTION_FINISH TIMESTAMP_NTZ(9))
RETURNS TABLE (NUMBER_OF_FILES NUMBER(38,0),ENTITY_TYPE VARCHAR(200), INGESTION_START TIMESTAMP_NTZ(9), INGESTION_FINISH TIMESTAMP_NTZ(9), STAGEDRECORDS NUMBER(38,0), CURATEDRECORDS NUMBER(38,0),REJECTEDRECORDS NUMBER(38,0), DIFF_HMS TIME(9))
LANGUAGE SQL
AS $$
   SELECT
   count(stagedrecords) as NUMBER_OF_FILES,
   ENTITY_TYPE,
   MIN(TS) AS INGESTION_START,
   MAX(TS) AS INGESTION_FINISH,
   SUM(STAGEDRECORDS) AS STAGEDRECORDS,
   SUM(CURATEDRECORDS) AS CURATEDRECORDS,
   SUM(CURATEDREJECTEDRECORDS) AS REJECTEDRECORDS,
   TIME_FROM_PARTS(0,0,TIMESTAMPDIFF(SECOND, INGESTION_START::TIMESTAMP, INGESTION_FINISH::TIMESTAMP)) AS DIFF_HMS
   FROM
   STATS
   WHERE TS >= INGESTION_START and ts <= INGESTION_FINISH 
   GROUP BY
   ENTITY_TYPE
   $$;


/*
   EXAMPLE
*/
select *  from  table(PSR_REPORT(TO_TIMESTAMP('2022-06-22 19:30:41.617', 'YYYY-MM-DD HH24:MI:SS.FF3'),TO_TIMESTAMP('2022-07-22 20:30:41.617', 'YYYY-MM-DD HH24:MI:SS.FF3')));